print("Name: Joe Nuts")
print("Jumpforce: 12")
print("Special power: Super intelligence")
print("Speed: Boundless")
print("Bike: Oppressor MK II")
print("Lives left: Joe Nuts doesn't die.")
print("Ammo: infinity")
print("Number of lasers: infinity")
print("Battery power: Unlimited")
print("Level: Maximum")
print("Wanted: Duh")